Feature/xtext editor
CVWRSM/cvwrsm pull request #144
Opened 2024-10-25 17:54 UTC by jmdegeorge

Refactoring xtext editor and ui into root modules. Building OSGI jars with bnd and deploying through github actions.

2024-10-25 21:09 UTC, jmdegeorge commented
@hxiedwr Hao, now that we have xtext-editor and xtext-editor-ui jars building through devops, do you have a suggested panel or action we can look for in the WRIMS GUI as a smoke test that the new jars are working as expected?

2024-10-25 21:40 UTC, hxiedwr commented
https://data.cnra.ca.gov/dataset/wrims-2-gui/resource/d3aab73a-0049-4a2c-90d3-592bb5386ea3

Here is a wrims demo. I think we need be able to repeat all the processes in the video.

Also you may need a few models to test. Here are a few latest models which only work after you merge the changes from master to wrims_devops

https://data.cnra.ca.gov/dataset/final-dcr-2023-calsim3-modelsels
________________________________
From: Joshua DeGeorge ***@***.***>
Sent: Friday, October 25, 2024 2:10:04 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Xie, ***@***.*** ***@***.***>; Mention ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Feature/xtext editor (PR #144)


@hxiedwr<https://github.com/hxiedwr> Hao, now that we have xtext-editor and xtext-editor-ui jars building through devops, do you have a suggested panel or action we can look for in the WRIMS GUI as a smoke test that the new jars are working as expected?

—
Reply to this email directly, view it on GitHub<https://github.com/CentralValleyModeling/wrims/pull/144#issuecomment-2438863975>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7C7KUEPWDM4H7PQ5B3DC3Z5KXSZAVCNFSM6AAAAABQTYGCPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZYHA3DGOJXGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-28 17:53 UTC, hxiedwr commented on xtext-editor/build.gradle
Will this Antlr generator create any "@override" annotation errors?

2024-10-29 17:58 UTC, jmdegeorge commented on xtext-editor/build.gradle
Hao, thanks for that demo video it's very helpful. 
Regarding the code generation, it looks like there's a lot of generated classes that were already to the xtext packages and some have manual modifications that were committed. Assuming that we don't want it overriding manual changes, I generated the missing the classes with antlr and manually combined everything into the src directories for the xtext-editor and xtext-editor-ui to build the OSGI module. Do you expect it to regenerate the xtext module classes on every build? Or can that continue to be a manual process that is performed as needed?

2024-10-29 20:17 UTC, hxiedwr commented on xtext-editor/build.gradle
I think if we can make xtext classes generation into the gradle auto process, that will be great. The reason is that now management wants to have WRIMS released every half year, which is on the similar time frame xText grammar may be changed. I think there are @override annotation errors which need to be fixed before it can be automated.

However, if we can't make it happen, I am also fine with manual xtext class generation.

2024-10-30 19:33 UTC, adamkorynta requested changes

2024-10-30 19:33 UTC, adamkorynta commented on xtext-editor/build.gradle
> +    implementation libs.guice
Shouldn't all of these come from third-party? also remove commented out code

2024-10-30 19:33 UTC, adamkorynta commented on xtext-editor-ui/build.gradle
> +    implementation libs.guice
Same comment abuout third-party and commented out code

2024-11-05 22:43 UTC, adamkorynta commented on third-party/build.gradle
> +    api fileTree(dir: 'libs/win-x64', include: ['cb.dll'])
These should be removed now right?

2024-11-05 23:09 UTC, adamkorynta commented on third-party/build.gradle
> +    api fileTree(dir: 'libs/win-x64', include: ['cb.dll'])
removing in PR: https://github.com/CentralValleyModeling/wrims/pull/151

2024-11-05 23:17 UTC, adamkorynta commented on xtext-editor/build.gradle
> +    implementation libs.guice
Resolving in PR: https://github.com/CentralValleyModeling/wrims/pull/151

2024-11-05 23:17 UTC, adamkorynta commented on xtext-editor-ui/build.gradle
> +    implementation libs.guice
Resolving in PR: https://github.com/CentralValleyModeling/wrims/pull/151

2024-11-05 23:18 UTC, adamkorynta commented on xtext-editor/build.gradle
Josh is logging a ticket to track this.

2024-11-05 23:19 UTC, adamkorynta commented
PR: https://github.com/CentralValleyModeling/wrims/pull/151 was rebased onto this work and all changes will get wrapped up into there.

2024-11-05 23:19 UTC, closed without merging