update to only read the condensed catalog once
CVWRSM/cvwrsm pull request #176
Opened 2024-12-05 01:17 UTC by adamkorynta

Fixes #167

The condensed catalogs were getting read in DSSFileView, then read again in the DSSCatalogView. Rewrote the logic to move the progress indicators into DSSFileView and then only access the cached condensed catalog in DSSCatalogView.

Moving the progress indicators also improves the UX and moves file load off of the UI thread.

2024-12-05 19:43 UTC, rma-tom requested changes
I built a jar with the revised code, and the DTS tab in the DSS perspective didn't open properly when I tried running with it, but it works with the jar from Feature/devOps

@hxiedwr should have a look

Here's the top of the stack trace:
!ENTRY org.eclipse.e4.ui.workbench 4 0 2024-12-05 11:38:18.648
!MESSAGE
!STACK 0
java.lang.IllegalArgumentException: Catalog is empty ?
        at vista.db.dss.DSSCatalogReader.readCatalog(DSSCatalogReader.java:95)
        at vista.db.dss.DSSCatalogReader.<init>(DSSCatalogReader.java:82)
        at vista.db.dss.DSSUtil.createCatalogReader(DSSUtil.java:562)
        at vista.db.dss.DSSGroup.getInitializedGroup(DSSGroup.java:108)
        at vista.set.GroupProxy.initializeGroup(GroupProxy.java:205)
        at vista.set.GroupProxy.getNumberOfDataReferences(GroupProxy.java:77)
        at calsim.app.Project.setDVHashtable(Project.java:115)
        at gov.ca.dwr.hecdssvue.components.DataOps.setProject(DataOps.java:524)
        at gov.ca.dwr.hecdssvue.views.DTSView.createPartControl(DTSView.java:49)
        at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:141)

2024-12-05 22:49 UTC, hxiedwr commented
Seems vista is used here. Can RMA go ahead removed the usage of vista? I thought you already removed the dependence on vista.jar, right?

2024-12-05 22:57 UTC, hxiedwr commented
By the way, I am not a better expert on HecLib 7 than  RMA. So you just need report the issue & fix it. If you still have issues, I am able to work on it but I am not sure if I can do it.

2024-12-06 17:11 UTC, adamkorynta commented
@hxiedwr - the wrims engine and comparison report tool no longer have Vista dependencies, however the CalSim dependency uses Vista (which is what is getting hit in this case). We'd either need to fully remove CalSim as well, or update CalSim to no longer use Vista.

2024-12-06 17:30 UTC, adamkorynta commented on dwr-hecdssvue/src/main/java/gov/ca/dwr/hecdssvue/views/DSSFileView.java
> -		//DataOps.setProject();
@hxiedwr - this commented out line is similar to what we are hitting. Why was this line commented out and do we even need to call it in the DTSView.createPartControl anymore?

2024-12-06 17:34 UTC, adamkorynta commented on dwr-hecdssvue/src/main/java/gov/ca/dwr/hecdssvue/views/DSSFileView.java
> -		//DataOps.setProject();
https://github.com/CentralValleyModeling/wrims/commit/428f5098dc81ae91a3ed153444120ead3d65a012

2024-12-06 17:39 UTC, adamkorynta commented
@hxiedwr - this PR did not effect the bug and we figured out that it manifests when the DSS perspective isn't already loaded. We can address the issue in a separate code change and issue.

2024-12-06 17:44 UTC, adamkorynta commented on dwr-hecdssvue/src/main/java/gov/ca/dwr/hecdssvue/views/DSSFileView.java
> -		//DataOps.setProject();
I created issue: https://github.com/CentralValleyModeling/wrims/issues/178

2024-12-06 17:46 UTC, rma-tom approved these changes
DTS tab issue was not related to this PR. No problems identified in the code changes for this PR.

2024-12-06 17:47 UTC, merged